server:
  port: 8085

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      # 限制最大上传文件大小
      max-file-size: 200MB
      # 限制最大请求携带内容大小
      max-request-size: 100MB
  application:
    # 应用名
    name: boot-manage
  datasource:
    hikari:
      # 最小空闲数量
      minimum-idle: 5
      # 空闲连接存活最大时间
      idle-timeout: 180000
      # 连接池最大数量
      maximum-pool-size: 15
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 数据库连接池超时时间
      connection-timeout: 30000
      # 连接测试查询
      connection-test-query: SELECT 1

# saToken 相关配置
sa-token:
  # 自定义jwt秘钥
  jwt-secret-key: "zuuuYao-1NiJ9.eyJsb2dpbklkI"

# mybatisPlus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  typeAliasesPackage: org.github.zuuuyao.entity
  type-enums-package: org.github.zuuuyao.entity.enums
  global-config:
    db-config:
      id-type: AUTO
    banner: true
  configuration:
    #开启驼峰功能
    map-underscore-to-camel-case: true
    cache-enabled: true

# springdoc-openapi 配置
springdoc:
  info:
    title: boot-manage
  swagger-ui:
    version: 1.0.0
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: '全部接口'
      paths-to-match: '/**'
      # controller所在包
      packages-to-scan: org.github.zuuuyao

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  # 自定义文档 group要和group-configs:group 保持一致
  documents:
    - group: 全部接口
      name: 其它文档
      locations: classpath:markdown/*
  basic:
    # 开启访问权限控制
    enable: true
    # 访问账户
    username: admin
    # 访问密码
    password: admin@123
  setting:
    # 是否开启自定义主页
    enable-home-custom: false
    # 自定义主页md文件位置,将某个.md 设置为主页
    home-custom-path: classpath:markdown/home.md
    # 设置语言
    language: zh_cn
    # 开启自定义swagger-models
    enable-swagger-models: true
    # 自定义swagger-models名称
    swagger-model-name: DTO请求参数模型(swagger-models)
    # 显示默认页脚
    enable-footer: true
    # 开启自定义页脚
    enable-footer-custom: true
    # 自定义页脚内容
    footer-custom-content: Apache License 2.0 | Copyright  2024-[Github-zuuuYao-boot-manage](https://github.com/HuangZhongYao/boot-manage)

#日志
logging:
  level:
    root: info
    com.baomidou.mybatisplus.samples.pagination: info
    org.springframework.web: info
    java.sql: info
  # 日志配置文件
  config: classpath:logback-spring.xml
  # 日志文件位置, 默认值当前目录 boot-manage-logs
  path: boot-manage-logs
