spring:
  profiles:
    active: dev
#日志
logging:
  level:
    root: info
    com.baomidou.mybatisplus.samples.pagination: info
    org.springframework.web: info
    java.sql: info
  # 日志配置文件
  config: classpath:logback-spring.xml
  # 日志文件位置, 默认值当前目录 boot-manage-logs
  path: boot-manage-logs

