server:
  port: 8085

spring:
  profiles:
    active: prod
  servlet:
    multipart:
      # 限制最大上传文件大小
      max-file-size: 200MB
      # 限制最大请求携带内容大小
      max-request-size: 100MB
  application:
    # 应用名
    name: boot-manage
  datasource:
    hikari:
      # 最小空闲数量
      minimum-idle: 5
      # 空闲连接存活最大时间
      idle-timeout: 180000
      # 连接池最大数量
      maximum-pool-size: 15
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 数据库连接池超时时间
      connection-timeout: 30000
      # 连接测试查询
      connection-test-query: SELECT 1
  jackson:
    # 配置jackson Date日期类型全局格式化
    date-format: yyyy-MM-dd HH:mm:ss
    # 配置jackson LocalDate类型全局格式化
    local-date-format: yyyy-MM-dd
    # 配置时区
    time-zone: Asia/Shanghai
# saToken 相关配置
sa-token:
  # 生成token 自定义jwt秘钥
  jwt-secret-key: "zuuuYao-1NiJ9.eyJsb2dpbklkI"
  # token请求头名称
  token-name: Authorization
  # token前缀
  token-prefix: "Bearer"
  # 是否尝试从 cookie 里读取 Token，此值为 false 后，StpUtil.login(id) 登录时也不会再往前端注入Cookie
  is-read-cookie: false
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 604800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）同设备登录会挤掉,不同设备不受影响
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # 是否输出操作日志
  is-log: true
  # 日志等级（trace、debug、info、warn、error、fatal）
  log-level: info

# mybatisPlus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  typeAliasesPackage: org.github.zuuuyao.entity
  type-enums-package: org.github.zuuuyao.entity.enums
  global-config:
    db-config:
      id-type: AUTO
    banner: true
  configuration:
    #开启驼峰功能
    map-underscore-to-camel-case: true
    cache-enabled: true

# springdoc-openapi 配置
springdoc:
  info:
    title: boot-manage
  swagger-ui:
    version: 1.0.0
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: '全部接口'
      paths-to-match: '/**'
      # controller所在包
      packages-to-scan: org.github.zuuuyao

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  # 自定义文档 group要和group-configs:group 保持一致
  documents:
    - group: 全部接口
      name: 全局返回值说明
      locations: classpath:markdown/*.md

  basic:
    # 开启访问权限控制
    enable: true
    # 访问账户
    username: admin
    # 访问密码
    password: admin@123
  setting:
    # 是否开启自定义主页
    enable-home-custom: false
    # 自定义主页md文件位置,将某个.md 设置为主页
    home-custom-path: classpath:markdown/home.md
    # 设置语言
    language: zh_cn
    # 开启自定义swagger-models
    enable-swagger-models: true
    # 自定义swagger-models名称
    swagger-model-name: DTO请求参数模型(swagger-models)
    # 显示默认页脚
    enable-footer: true
    # 开启自定义页脚
    enable-footer-custom: true
    # 自定义页脚内容
    footer-custom-content: Apache License 2.0 | Copyright  2024-[Github-zuuuYao-boot-manage](https://github.com/HuangZhongYao/boot-manage)

#日志
logging:
  level:
    root: info
    com.baomidou.mybatisplus.samples.pagination: info
    org.springframework.web: info
    java.sql: info
    org.github.zuuuyao: debug
  # 日志配置文件
  config: classpath:logback-spring.xml
  # 日志文件位置, 默认值当前目录 boot-manage-logs
  path: boot-manage-logs
